import {z} from 'zod';
export const fieldStates=['Actual','Planned','Not yet determined'] as const;
export const offeringStatuses=['Scouting','Coming Soon','Available','Fully Subscribed','Past Project'] as const;
export const categories=['Mountains','Farms','Coast','Desert','Heritage','Unclassified'] as const;
const description=z.string().trim().max(6000);
export function stated<T extends z.ZodType>(value:T){return z.object({value:value.nullable(),state:z.enum(fieldStates),notes:description.optional()}).superRefine((input,c)=>{const f=input as {state:string;value:unknown};if(f.state!=='Not yet determined'&&(f.value===null||f.value===''))c.addIssue({code:'custom',message:'A known or planned field needs a value.'});});}
const count=z.number().int().nonnegative(), amount=z.number().nonnegative();
export const factDefinitions={
 state:{label:'State / province',group:'Location',type:'text'},county:{label:'County',group:'Location',type:'text'},country:{label:'Country',group:'Location',type:'text'},elevation:{label:'Elevation (feet)',group:'Location',type:'number'},
 total_acres:{label:'Total acres',group:'The land',type:'number'},topography:{label:'Topography',group:'The land',options:['flat','rolling','steep','mixed']},tree_cover:{label:'Tree cover',group:'The land',type:'text'},water_features:{label:'Water features',group:'The land',type:'text'},views:{label:'Views',group:'The land',type:'text'},notable_natural_features:{label:'Notable natural features',group:'The land',type:'text'},adjacency:{label:'Adjacency',group:'The land',type:'text'},
 road_access:{label:'Road access',group:'Access & infrastructure',options:['paved','gravel','seasonal']},year_round_access:{label:'Year-round access',group:'Access & infrastructure',type:'boolean'},winter_access_notes:{label:'Winter access notes',group:'Access & infrastructure',type:'text'},power:{label:'Power',group:'Access & infrastructure',type:'text'},water_source:{label:'Water source',group:'Access & infrastructure',type:'text'},septic_sewer:{label:'Septic / sewer',group:'Access & infrastructure',type:'text'},connectivity:{label:'Connectivity',group:'Access & infrastructure',type:'text'},gated:{label:'Gated',group:'Access & infrastructure',type:'boolean'},
 development_stage:{label:'Development stage',group:"What’s there & what’s planned",options:['raw','entitled','permitted','under construction','built']},existing_structures:{label:'Existing structures',group:"What’s there & what’s planned",type:'text'},planned_structures:{label:'Planned structures',group:"What’s there & what’s planned",type:'text'},shared_amenities:{label:'Shared amenities',group:"What’s there & what’s planned",type:'text'},completion_timeline:{label:'Completion timeline',group:"What’s there & what’s planned",type:'text'},
 total_shares:{label:'Total shares',group:'Ownership & cost',type:'number'},shares_available:{label:'Shares available',group:'Ownership & cost',type:'number'},share_price:{label:'Share price',group:'Ownership & cost',type:'money'},what_a_share_conveys:{label:'What a share conveys',group:'Ownership & cost',type:'text'},annual_dues:{label:'Annual dues',group:'Ownership & cost',type:'money'},dues_frequency:{label:'Dues frequency',group:'Ownership & cost',options:['monthly','quarterly','annual']},dues_include:{label:'Dues include',group:'Ownership & cost',type:'text'},usage_allocation:{label:'Usage allocation',group:'Ownership & cost',type:'text'},financing_available:{label:'Financing available',group:'Ownership & cost',type:'boolean'},
 apn:{label:'Parcel / APN',group:'Parcel & legal',type:'text'},zoning:{label:'Zoning',group:'Parcel & legal',type:'text'},permitted_uses:{label:'Permitted uses',group:'Parcel & legal',type:'text'},easements_covenants:{label:'Easements & covenants',group:'Parcel & legal',type:'text'},ownership_entity_structure:{label:'Ownership entity',group:'Parcel & legal',type:'text'},
 season_notes:{label:'Season notes',group:'Setting',type:'text'},activity_tags:{label:'Activities',group:'Setting',type:'tags'},recreation:{label:'Recreation',group:'Things to do',type:'text'},nearby_attractions:{label:'Nearby attractions',group:'Things to do',type:'text'},seasonal_events:{label:'Seasonal events',group:'Things to do',type:'text'},
} as const;
export type FactKey=keyof typeof factDefinitions;
export type FactDefinition={label:string;group:string;type?:string;options?:readonly string[]};
const shape=Object.fromEntries(Object.entries(factDefinitions).map(([key,d])=>{
 const def:FactDefinition=d;
 const value=def.options?z.enum(def.options as [string,...string[]]):def.type==='number'?(key.includes('shares')?count:key==='elevation'?z.number():amount):def.type==='money'?amount:def.type==='boolean'?z.boolean():def.type==='tags'?z.array(z.string().trim().min(1).max(100)).max(40):description.min(1);
 return [key,stated(value).optional()];
})) as unknown as Record<FactKey,z.ZodOptional<ReturnType<typeof stated>>>;
export const factsSchema=z.object(shape).strict().transform(v=>v as PropertyFacts);
export type PropertyFact={value:string|number|boolean|string[]|null;state:typeof fieldStates[number];notes?:string};
export type PropertyFacts=Partial<Record<FactKey,PropertyFact>>;
export const coordinatesSchema=stated(z.object({latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180),precision:z.enum(['approximate','parcel'])}));
export const proximitySchema=z.object({id:z.string().min(1).max(100),name:z.string().trim().min(1).max(200),kind:z.enum(['airport','town','metro','anchor']),minutes:stated(amount),miles:stated(amount),notes:description.default('')});
export const phaseSchema=z.object({id:z.string().min(1).max(100),name:z.string().trim().min(1).max(200),scope:description,budget:stated(amount),timeline:stated(description.min(1))});
export const assetUrl=z.string().refine(v=>/^\/images\/[a-zA-Z0-9._-]+$/.test(v)||(/^https:\/\//.test(v)&&!/[\s'"<>\\]/.test(v)), 'Use a local library path or HTTPS media URL.');
export const mediaSchema=z.object({id:z.string().min(1).max(100),role:z.enum(['render','site_plan','parcel_map','aerial','video_tour','gallery']),url:assetUrl,kind:z.enum(['image','video','document']),alt:z.string().trim().min(1).max(300),caption:description,state:z.enum(fieldStates)});
export function formatFact(f:PropertyFact,currency='USD',money=false){if(f.state==='Not yet determined')return 'Not yet determined';const value=typeof f.value==='boolean'?(f.value?'Yes':'No'):typeof f.value==='number'?(money?new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:0}).format(f.value):f.value.toLocaleString('en-US')):Array.isArray(f.value)?f.value.join(', '):f.value??'';return `${value}${f.state==='Planned'?' (planned)':''}`;}
export function travelTime(minutes:number){const hours=Math.floor(minutes/60),rest=minutes%60;return hours?`${hours} hr${rest?` ${rest} min`:''}`:`${rest} min`;}
