'use client';
import {useRef,useState} from 'react';
import type {GroupDocument,DocumentAudience} from '@/lib/group-documents';
import {roleLabels,roleValues,type ClubRole} from '@/lib/roles';
import {TagEditor} from '@/components/member-documents';
import {MultiFilter} from '@/components/table-filter';
import {DataTable,type TableColumn} from '@/components/data-table';
import filterStyles from '../members/members.module.css';
import styles from './documents.module.css';
type Property={id:string;name:string};
type Column='filename'|'properties'|'audience'|'tags'|'edit';
const columns:TableColumn<Column>[]=[{key:'filename',label:'Document Name',width:260,min:160},{key:'properties',label:'Property',width:210,min:130},{key:'audience',label:'Audience',width:180,min:140},{key:'tags',label:'Tags',width:190,min:140},{key:'edit',label:'Edit',width:75,min:70,sortable:false}];
const blankAudience:DocumentAudience={everyone:false,propertyIds:[],roles:[]};
const valid=(a:DocumentAudience)=>a.everyone||!!(a.propertyIds.length||a.roles.length);
const audienceLabel=(doc:GroupDocument)=>doc.everyone?'Everyone':doc.roles.length?doc.roles.map(role=>roleLabels[role]).join(', '):'All associated members';
function AudienceEditor({value,onChange,properties}:{value:DocumentAudience;onChange:(a:DocumentAudience)=>void;properties:Property[]}){
 return <div className={styles.audience}><label>Who can access this document?<select value={value.everyone?'everyone':'groups'} onChange={e=>onChange(e.target.value==='everyone'?{everyone:true,propertyIds:[],roles:[]}:blankAudience)}><option value="groups">Selected groups</option><option value="everyone">Everyone in the club</option></select></label>{!value.everyone&&<><div className={styles.filters}><MultiFilter label="Properties" options={properties} selected={value.propertyIds} onChange={propertyIds=>onChange({...value,propertyIds})}/><MultiFilter label="Club roles" options={roleValues.map(role=>({id:role,name:roleLabels[role]}))} selected={value.roles} onChange={roles=>onChange({...value,roles:roles as ClubRole[]})}/></div><p>Choose properties, club roles, or both. With both selected, members must match a selected property and a selected club role.</p></>}{value.everyone&&<p>Available to every signed-in club member.</p>}</div>;
}
function GroupRow({doc,properties,onUpdate}:{doc:GroupDocument;properties:Property[];onUpdate:(doc:GroupDocument)=>void}){
 const [editing,setEditing]=useState(false),[tags,setTags]=useState(doc.tags),[audience,setAudience]=useState<DocumentAudience>({everyone:doc.everyone,propertyIds:doc.property_ids,roles:doc.roles}),[pending,setPending]=useState(false),[error,setError]=useState('');
 async function save(){setPending(true);setError('');try{const r=await fetch(`/api/group-documents/${doc.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:doc.version,tags,audience})});const data=await r.json();if(!r.ok)throw new Error(data.error);onUpdate(data.document);setEditing(false);}catch(e){setError(e instanceof Error?e.message:'Could not save changes.');}finally{setPending(false);}}
 return <><tr><td><a className={styles.filename} href={`/api/group-documents/${doc.id}`} download={doc.filename}>{doc.filename}</a><small className={styles.size}>{doc.byte_size<1048576?`${Math.ceil(doc.byte_size/1024)} KB`:`${(doc.byte_size/1048576).toFixed(1)} MB`}</small></td><td>{doc.property_names.join(', ')||'—'}</td><td>{audienceLabel(doc)}</td><td><div className={styles.tags}>{doc.tags.map(tag=><span key={tag}>{tag}</span>)}</div></td><td><button type="button" className={`secondary ${styles.edit}`} disabled={pending} aria-label={`Edit ${doc.filename}`} aria-expanded={editing} onClick={()=>{setAudience({everyone:doc.everyone,propertyIds:doc.property_ids,roles:doc.roles});setTags(doc.tags);setError('');setEditing(!editing);}}>{editing?'Cancel':'Edit'}</button></td></tr>{editing&&<tr><td colSpan={5}><fieldset className={styles.editor} disabled={pending}><AudienceEditor value={audience} onChange={setAudience} properties={properties}/><TagEditor tags={tags} onChange={setTags} suggestions={[]} disabled={pending}/><div className={styles.actions}><button type="button" disabled={pending||!valid(audience)} onClick={()=>void save()}>{pending?'Saving…':'Save changes'}</button></div></fieldset>{error&&<p role="alert" className={styles.error}>{error}</p>}</td></tr>}</>;
}
export function GroupDocumentManager({initial,properties}:{initial:GroupDocument[];properties:Property[]}){
 const [docs,setDocs]=useState(initial),[search,setSearch]=useState(''),[selectedProperties,setProperties]=useState<string[]>([]),[selectedRoles,setRoles]=useState<string[]>([]),[sort,setSort]=useState<{column:Column;direction:'asc'|'desc'}>({column:'filename',direction:'asc'});
 const [tags,setTags]=useState<string[]>([]),[audience,setAudience]=useState<DocumentAudience>(blankAudience),[pending,setPending]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');const form=useRef<HTMLFormElement>(null);
 const sortedProperties=[...properties].sort((a,b)=>a.name.localeCompare(b.name));
 function sortValue(doc:GroupDocument){return sort.column==='properties'?doc.property_names.join(', '):sort.column==='audience'?audienceLabel(doc):sort.column==='tags'?doc.tags.join(', '):doc.filename;}
 const terms=search.toLowerCase().trim().split(/\s+/).filter(Boolean);
 const visible=docs.filter(doc=>terms.every(term=>`${doc.filename} ${doc.property_names.join(' ')} ${audienceLabel(doc)} ${doc.tags.join(' ')}`.toLowerCase().includes(term))&&(!selectedProperties.length||doc.property_ids.some(id=>selectedProperties.includes(id)))&&(!selectedRoles.length||doc.roles.some(role=>selectedRoles.includes(role)))).sort((a,b)=>sortValue(a).localeCompare(sortValue(b),undefined,{numeric:true,sensitivity:'base'})*(sort.direction==='asc'?1:-1));
 function clear(){setSearch('');setProperties([]);setRoles([]);}
 async function upload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(pending||!valid(audience))return;const data=new FormData(event.currentTarget);const file=data.get('file');if(!(file instanceof File)||!file.size||file.size>20*1048576){setError('Choose a nonempty file up to 20 MB.');return;}data.set('tags',JSON.stringify(tags));data.set('audience',JSON.stringify(audience));setPending(true);setError('');setSuccess('');try{const r=await fetch('/api/group-documents',{method:'POST',body:data});const result=await r.json();if(!r.ok)throw new Error(result.error);setDocs(current=>[result.document,...current]);setTags([]);setAudience(blankAudience);form.current?.reset();clear();setSuccess('Document uploaded. Matching members can now find it in Documents.');}catch(e){setError(e instanceof Error?e.message:'Upload failed. Please try again.');}finally{setPending(false);}}
 return <><p className={styles.intro}>Share documents with groups of members. Manage private, individual files in Member Details.</p><div className={filterStyles.directoryTools}><label className={filterStyles.search}><span className={filterStyles.srOnly}>Search group documents</span><input type="search" placeholder="Search files, properties, roles or tags" value={search} onChange={e=>setSearch(e.target.value)}/></label><MultiFilter label="Properties" options={sortedProperties} selected={selectedProperties} onChange={setProperties}/><MultiFilter label="Club roles" options={roleValues.map(role=>({id:role,name:roleLabels[role]}))} selected={selectedRoles} onChange={setRoles}/>{(search||selectedProperties.length>0||selectedRoles.length>0)&&<button type="button" className={`secondary ${filterStyles.clearFilters}`} onClick={clear}>Clear all</button>}</div><DataTable columns={columns} label="Group documents" widthStorageKey="land-club:group-documents:column-widths" sort={sort} onSort={column=>setSort({column,direction:sort.column===column&&sort.direction==='asc'?'desc':'asc'})}>{visible.map(doc=><GroupRow key={doc.id} doc={doc} properties={sortedProperties} onUpdate={updated=>setDocs(current=>current.map(row=>row.id===updated.id?updated:row))}/>)}{!visible.length&&<tr><td colSpan={5}>{docs.length?'No documents match your filters.':'No group documents yet.'}</td></tr>}</DataTable><form ref={form} className={styles.upload} onSubmit={upload}><h2>Upload a document</h2><fieldset className={styles.editor} disabled={pending}><label className={styles.file}>File<input type="file" name="file" required accept=".pdf,.docx,.xlsx,.csv,.txt,.png,.jpg,.jpeg"/></label><p className={styles.help}>PDF, Word, Excel, CSV, text or images · up to 20 MB</p><AudienceEditor value={audience} onChange={setAudience} properties={sortedProperties}/><TagEditor tags={tags} onChange={setTags} suggestions={[]} disabled={pending}/><p className={styles.help}>Tags help with searching; the audience above controls access.</p><div className={styles.actions}><button disabled={pending||!valid(audience)}>{pending?'Uploading…':'Upload document'}</button></div></fieldset>{error&&<p role="alert" className={styles.error}>{error}</p>}{success&&<p role="status" className={styles.help}>{success}</p>}</form></>;
}
