'use client';
import {useActionState,useState} from 'react';
import {requestPasswordReset,signIn} from './actions';
export function SignInForm(){
 const [mode,setMode]=useState<'signin'|'signup'|'recovery'>('signin');
 return <><div className="auth-tabs"><button type="button" className={mode==='signin'?'':'secondary'} aria-pressed={mode==='signin'} onClick={()=>setMode('signin')}>Sign in</button><button type="button" className={mode==='signup'?'':'secondary'} aria-pressed={mode==='signup'} onClick={()=>setMode('signup')}>Create account</button></div>{mode==='signin'?<CredentialsForm onForgotPassword={()=>setMode('recovery')}/>:mode==='recovery'?<RecoveryForm onBack={()=>setMode('signin')}/>:<section className="panel"><span className="eyebrow">BY INVITATION</span><h2>Your next chapter starts here.</h2><p>Land Club accounts are currently invitation-only. Please contact your Land Club representative to have an account created for you.</p><p className="muted">Property memberships and staff access are assigned separately. If your account is already set up, you can sign in below.</p><button className="secondary" onClick={()=>setMode('signin')}>I already have an account</button></section>}</>;
}
function CredentialsForm({onForgotPassword}:{onForgotPassword:()=>void}){const [state,action,pending]=useActionState(signIn,{error:''});return <form action={action} className="form"><label>Email<input type="email" name="email" autoComplete="username" required maxLength={254}/></label><label>Password<input type="password" name="password" autoComplete="current-password" required maxLength={1024}/></label><button type="button" className="text auth-recovery-link" onClick={onForgotPassword}>Forgot your password?</button>{state.error&&<p className="cms-error" role="alert">{state.error}</p>}<button disabled={pending}>{pending?'Signing in…':'Sign in to Land Club'}</button></form>}
function RecoveryForm({onBack}:{onBack:()=>void}){const [state,action,pending]=useActionState(requestPasswordReset,{error:''});return <section className="panel auth-recovery"><span className="eyebrow">PASSWORD RECOVERY</span><h2>Reset your password.</h2><p>Enter the email address for your account. We’ll send you a secure link to choose a new password.</p>{state.message?<><p className="cms-success" role="status">{state.message}</p><button type="button" className="secondary" onClick={onBack}>Return to sign in</button></>:<form action={action} className="form"><label>Email<input type="email" name="email" autoComplete="email" required maxLength={254} autoFocus/></label>{state.error&&<p className="cms-error" role="alert">{state.error}</p>}<button disabled={pending}>{pending?'Sending link…':'Send reset link'}</button><button type="button" className="text" onClick={onBack}>Back to sign in</button></form>}</section>}
