'use client';
import {useState,useTransition} from 'react';
import Link from 'next/link';
import type {ClubEvent} from '@/lib/events';
import {saveEvent} from './actions';
const empty={title:'',description:'',start:'',end:'',location:'',meetingUrl:'',status:'scheduled' as 'scheduled'|'cancelled'|'archived'};
function localDate(iso:string){const d=new Date(iso);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;}
export function EventManager({initial}:{initial:ClubEvent[]}){
 const [events,setEvents]=useState(initial);const [editing,setEditing]=useState<ClubEvent|null>(null);const [form,setForm]=useState(empty);const [open,setOpen]=useState(false);const [timeZone,setTimeZone]=useState('UTC');const [message,setMessage]=useState('');const [error,setError]=useState('');const [pending,startTransition]=useTransition();
 function edit(event?:ClubEvent){setEditing(event||null);setForm(event?{...event.details,start:localDate(event.details.startsAt),end:localDate(event.details.endsAt)}:empty);setTimeZone(Intl.DateTimeFormat().resolvedOptions().timeZone);setOpen(true);setError('');setMessage('');}
 return <><div className="row-actions"><button disabled={pending} onClick={()=>edit()}>Create event</button><Link className="button secondary" href="/staff/events">View member events</Link></div>
 {open&&<section className="panel"><h2>{editing?'Edit event':'New event'}</h2><p>Saving makes this event visible to every member unless its status is Archived.</p><form className="form" onSubmit={e=>{e.preventDefault();setError('');setMessage('');startTransition(async()=>{try{const result=await saveEvent({title:form.title,description:form.description,location:form.location,meetingUrl:form.meetingUrl,status:form.status,startsAt:new Date(form.start).toISOString(),endsAt:new Date(form.end).toISOString(),timeZone},editing?.id,editing?.version);if(result.error){setError(result.error);return;}if(result.event){const event=result.event;setEvents(rows=>[...rows.filter(row=>row.id!==event.id),event].sort((a,b)=>a.details.startsAt.localeCompare(b.details.startsAt)));setOpen(false);setMessage(event.details.status==='archived'?'Event archived and hidden from members.':'Event saved. Members can now see the latest details.');}}catch{setError('Unable to save. Check the dates and try again.');}});}}>
 <fieldset disabled={pending} className="event-fields"><label>Title<input required maxLength={150} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Description<textarea required maxLength={10000} rows={5} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><p className="muted">Enter times in your browser’s time zone: <strong>{timeZone}</strong>. Members see this time-zone label alongside the schedule.</p><div className="dashboard-grid"><label>Start<input required type="datetime-local" value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/></label><label>End<input required type="datetime-local" value={form.end} onChange={e=>setForm({...form,end:e.target.value})}/></label></div><label>Location<input required maxLength={300} placeholder="Venue and address, or Online" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Meeting or event link (optional)<input type="url" placeholder="https://" value={form.meetingUrl} onChange={e=>setForm({...form,meetingUrl:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as typeof form.status})}><option value="scheduled">Scheduled — visible to members</option><option value="cancelled">Cancelled — visible with cancellation notice</option><option value="archived">Archived — hidden from members</option></select></label></fieldset><div className="row-actions"><button disabled={pending}>{pending?'Saving…':'Save event'}</button><button type="button" className="secondary" disabled={pending} onClick={()=>{setOpen(false);setError('');}}>Cancel editing</button></div></form></section>}
 {error&&<p role="alert" className="cms-error">{error}</p>}{message&&<p role="status" className="cms-success">{message}</p>}
 {!events.length&&<div className="panel"><h2>Your first gathering starts here.</h2><p>Create an event to add it to the member Events section.</p></div>}
 {events.map(event=><article className="listrow" key={event.id}><div><span className="badge">{event.details.status}</span><h2>{event.details.title}</h2><p>{new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short',timeZone:event.details.timeZone}).format(new Date(event.details.startsAt))} · {event.details.timeZone}</p><p>{event.details.location}</p></div><button className="secondary" disabled={pending} aria-label={`Edit event: ${event.details.title}`} onClick={()=>edit(event)}>Edit event</button></article>)}</>;
}
