'use client';
import Script from 'next/script';
import {useEffect,useRef,useState} from 'react';
type Place={slug:string;name:string;category:string;status:string;region:string};
type MapInstance={remove():void;fitBounds(points:number[][],options:object):void;panTo(point:number[]):void};
type Leaflet={map(element:HTMLElement,options:object):MapInstance;tileLayer(url:string,options:object):{addTo(map:MapInstance):void;on(event:string,cb:()=>void):void};divIcon(options:object):unknown;marker(point:number[],options:object):{addTo(map:MapInstance):{on(event:string,cb:()=>void):void}}};
declare global {interface Window{L?:Leaflet}}
const regions:Record<string,number[]>={'norden-cross':[39.31,-120.34],'sutter-creek':[38.392,-120.803],'point-reyes':[38.069,-122.806],'pioneertown':[34.156,-116.498]};
export function CollectionMap({properties}:{properties:Place[]}){
 const [ready,setReady]=useState(false),[failed,setFailed]=useState(false),[selected,setSelected]=useState(properties[0]?.slug);const el=useRef<HTMLDivElement>(null),map=useRef<MapInstance|null>(null);
 useEffect(()=>{if(window.L)setReady(true);},[]);
 useEffect(()=>{if(!ready||!window.L||!el.current)return;const L=window.L;const instance=L.map(el.current,{scrollWheelZoom:false});map.current=instance;const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:16,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'});tiles.addTo(instance);tiles.on('tileerror',()=>setFailed(true));const points=properties.filter(p=>regions[p.slug]);for(const p of points){L.marker(regions[p.slug],{title:p.name+' — approximate region',icon:L.divIcon({className:'land-map-marker',html:'<span></span>',iconSize:[22,22],iconAnchor:[11,11]})}).addTo(instance).on('click',()=>setSelected(p.slug));}if(points.length)instance.fitBounds(points.map(p=>regions[p.slug]),{padding:[40,40],maxZoom:11});return()=>{instance.remove();map.current=null;};},[ready,properties]);
 const p=properties.find(p=>p.slug===selected)||properties[0];return <><Script src="/vendor/leaflet.js" onReady={()=>setReady(true)} onError={()=>setFailed(true)}/><div className="collection-map-layout"><div><div ref={el} className="discovery-map collection-map" aria-label="Interactive map of Land Club regions"/>{failed&&<p className="caption">Map imagery is unavailable. Choose a place from the list.</p>}</div><div><div className="map-place-picker">{properties.map(p=><button key={p.slug} className={selected===p.slug?'selected':''} onClick={()=>{setSelected(p.slug);if(regions[p.slug])map.current?.panTo(regions[p.slug]);}}>{p.name}</button>)}</div>{p&&<div className="map-detail"><div className="eyebrow">{p.category} / {p.status}</div><h3>{p.name}</h3><p>{p.region}</p><p className="caption">{regions[p.slug]?'Approximate region, not a surveyed property location.':'Location unconfirmed. No marker is placed on the map.'}</p><a className="text" href={'/properties/'+p.slug}>Open this story</a></div>}</div></div></>;
}
