import type {PropertyDraft} from '@/lib/schema';
import {CollectionMap} from './collection-map';
const chapters=[
 {id:'mountains',name:'Mountains',num:'01',intro:'High country. Deeper roots.',copy:'Start with Norden Cross: our flagship mountain-property story, with a development vision still taking shape.'},
 {id:'farms',name:'Farms',num:'02',intro:'A connection to the working land.',copy:'Past projects belong in the story, with their status made clear. Sutter Creek is context, not current inventory.'},
 {id:'coast',name:'Coast',num:'03',intro:'Where the story meets the sea.',copy:'A completed-home example and a regional scouting direction. Two different starting points for what comes next.'},
 {id:'desert',name:'Desert',num:'04',intro:'Room for the horizon.',copy:'The desert chapter carries past experience into an open-ended regional search.'}
];
export function DiscoveryHome({properties}:{properties:PropertyDraft[]}){
 const visible=chapters.filter(c=>properties.some(p=>p.category===c.name));
 return <main><div className="explore-intro"><div><div className="eyebrow">LAND CLUB / THE PLACES THAT BRING US TOGETHER</div><h1>Find your<br/><em>kind of somewhere.</em></h1></div><div><p>From the mountains to the coast, places with a character of their own. Explore what’s here, what’s taking shape, and where we’re looking next.</p><p className="muted">A working collection from the Land Club draft. Current ownership relationships and availability require confirmation.</p></div></div><nav className="sectionnav explore-nav" aria-label="Landscape chapters">{visible.map(c=><a key={c.id} href={'#'+c.id}>{c.name}</a>)}{properties.length>0&&<a href="#map">View the map</a>}</nav>{visible.map(c=>{const places=properties.filter(p=>p.category===c.name).sort((a,b)=>a.slug==='shelter-cove'?-1:b.slug==='shelter-cove'?1:a.name.localeCompare(b.name));return <section key={c.id} id={c.id} className="section landscape-chapter"><div className="chapter-heading"><span className="chapter-number">{c.num}</span><div><div className="eyebrow">{c.name}</div><h2>{c.intro}</h2></div><p>{c.copy}</p></div><div className={'chapter-properties '+(places.length>1?'two-places':'')}>{places.map(p=><article key={p.slug} className="discovery-property-card"><a className="chapter-photo" href={'/properties/'+p.slug}><img src={p.hero} alt={p.imageAlt} loading="lazy"/><span>{p.region}</span></a><div className="chapter-copy"><div className="eyebrow">{p.status}{p.isDemo?' · DEMO CONTENT':''}</div><h3>{p.name}</h3><p>{p.summary}</p><p className="caption">{p.gallery.find(im=>im.src===p.hero)?.caption||p.imageAlt}</p><div className="row-actions"><a className={'button'+(p.slug==='norden-cross'?'':' secondary')} href={'/properties/'+p.slug}>{p.status.startsWith('Past project')?'Read the past chapter':p.status==='Scouting area'?'Explore the region':'Explore the property'}</a></div></div></article>)}</div></section>})}{!properties.length&&<section className="section empty"><h2>The next chapter is taking shape.</h2><p>No property pages have been published yet.</p></section>}{properties.length>0&&<section id="map" className="section"><div className="heading"><div><div className="eyebrow">THE WIDER PICTURE</div><h2>One collection.<br/>Many ways to belong.</h2></div><p className="muted">Tap a marker to explore a place.<br/>All locations are regional references.</p></div><CollectionMap properties={properties.map(p=>({slug:p.slug,name:p.name,category:p.category,status:p.status,region:p.region}))}/><p className="caption">Markers locate regions, not parcels or property boundaries. Shelter Cove has no marker until its location is confirmed.</p></section>}</main>;
}
