'use client';
import {useEffect,useId,useRef,useState} from 'react';
import type {MemberDocument} from '@/lib/member-documents';
import styles from './member-documents.module.css';
import tableStyles from './data-table.module.css';

export function TagEditor({tags,onChange,suggestions,disabled}:{tags:string[];onChange:(tags:string[])=>void;suggestions:string[];disabled:boolean}){
 const [text,setText]=useState('');const id=useId();
 function add(){const tag=text.trim().slice(0,100);if(tag&&tags.length<30&&!tags.some(t=>t.toLowerCase()===tag.toLowerCase()))onChange([...tags,tag]);setText('');}
 return <div className={styles.tagEditor}><div className={styles.tags}>{tags.map(tag=><span key={tag}>{tag}<button type="button" disabled={disabled} aria-label={`Remove tag ${tag}`} onClick={()=>onChange(tags.filter(t=>t!==tag))}>×</button></span>)}</div><div className={styles.tagInput}><label><span className={styles.srOnly}>Document tag</span><input value={text} maxLength={100} disabled={disabled||tags.length>=30} list={id} placeholder="Add a property, role, or custom tag" onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add();}}}/></label><datalist id={id}>{suggestions.filter(s=>!tags.includes(s)).map(s=><option key={s} value={s}/>)}</datalist><button type="button" className="secondary" disabled={disabled||!text.trim()||tags.length>=30} onClick={add}>Add tag</button></div></div>;
}
function DocumentRow({doc,admin,suggestions,onUpdate}:{doc:MemberDocument;admin:boolean;suggestions:string[];onUpdate:(doc:MemberDocument)=>void}){
 const [editing,setEditing]=useState(false),[tags,setTags]=useState(doc.tags),[pending,setPending]=useState(false),[error,setError]=useState('');
 const propertyTags=doc.tags.filter(tag=>/^property:\s*\S/i.test(tag));
 const properties=doc.group?doc.property_names||[]:propertyTags.map(tag=>tag.replace(/^property:\s*/i,''));
 const otherTags=doc.group?doc.tags:doc.tags.filter(tag=>!propertyTags.includes(tag));
 async function save(){setPending(true);setError('');try{const r=await fetch(`/api/member-documents/${doc.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({tags,version:doc.version})});const result=await r.json();if(!r.ok)throw new Error(result.error);onUpdate(result.document);setEditing(false);}catch(e){setError(e instanceof Error?e.message:'Unable to save tags.');}finally{setPending(false);}}
 return <><tr><td className={styles.documentName}><a href={`/api/${doc.group?'group-documents':'member-documents'}/${doc.id}`} download={doc.filename}>{doc.filename}</a><small>{doc.byte_size<1024*1024?`${Math.ceil(doc.byte_size/1024)} KB`:`${(doc.byte_size/(1024*1024)).toFixed(1)} MB`}</small></td><td>{properties.length?properties.join(', '):<span className="muted">—</span>}</td><td><div className={styles.tags}>{otherTags.length?otherTags.map(tag=><span key={tag}>{tag}</span>):<span className={styles.noTags}>—</span>}</div></td>{admin&&<td className={styles.tableActions}><button type="button" className="secondary" disabled={pending} aria-label={`${editing?'Cancel editing tags for':'Edit tags for'} ${doc.filename}`} aria-expanded={editing} onClick={()=>{setTags(doc.tags);setError('');setEditing(!editing);}}>{editing?'Cancel':'Edit tags'}</button></td>}</tr>{editing&&<tr><td colSpan={admin?4:3}><TagEditor tags={tags} onChange={setTags} suggestions={suggestions} disabled={pending}/><div className={styles.actions}><button type="button" className="secondary" disabled={pending} onClick={()=>void save()}>{pending?'Saving…':'Save tags'}</button></div>{error&&<p role="alert" className={styles.error}>{error}</p>}</td></tr>}</>;

}
export function MemberDocuments({memberId,suggestions=[]}:{memberId?:string;suggestions?:string[]}){
 const admin=!!memberId;const [docs,setDocs]=useState<MemberDocument[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[tags,setTags]=useState<string[]>([]),[pending,setPending]=useState(false),[reload,setReload]=useState(0),[success,setSuccess]=useState('');
 const form=useRef<HTMLFormElement>(null);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setDocs([]);fetch('/api/member-documents'+(memberId?`?memberId=${encodeURIComponent(memberId)}`:''),{signal:controller.signal,cache:'no-store'}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);setDocs(data.documents);}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Unable to load documents.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[memberId,reload]);
 async function upload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(pending)return;const data=new FormData(event.currentTarget);const file=data.get('file');if(!(file instanceof File)||!file.size){setError('Choose a document.');return;}if(file.size>20*1024*1024){setError('Choose a file up to 20 MB.');return;}data.set('memberId',memberId!);data.set('tags',JSON.stringify(tags));setPending(true);setError('');setSuccess('');try{const r=await fetch('/api/member-documents',{method:'POST',body:data});const result=await r.json();if(!r.ok)throw new Error(result.error);setDocs(current=>[result.document,...current]);setSearch('');setTags([]);form.current?.reset();setSuccess('Document uploaded.');}catch(e){setError(e instanceof Error?e.message:'Unable to upload. Please try again.');}finally{setPending(false);}}
 const terms=search.toLowerCase().trim().split(/\s+/).filter(Boolean);const visible=docs.filter(doc=>terms.every(term=>`${doc.filename} ${doc.tags.join(' ')}`.toLowerCase().includes(term)));
 return <div className={styles.documents}>{admin&&<p className={styles.help}>Only this member and admins can access these files.</p>}<label className={styles.search}><span className={styles.srOnly}>Search documents</span><input type="search" placeholder="Search files or tags" value={search} onChange={e=>setSearch(e.target.value)}/></label>{loading?<p role="status">Loading documents…</p>:<>{visible.length?<div className={`${tableStyles.wrap} ${styles.tableWrap}`}><table className={`${tableStyles.table} ${styles.documentTable}`}><caption className={styles.srOnly}>Member documents</caption><thead><tr><th scope="col">Document Name</th><th scope="col">Property</th><th scope="col">Tags</th>{admin&&<th scope="col" className={styles.actionsColumn}><span className={styles.srOnly}>Actions</span></th>}</tr></thead><tbody>{visible.map(doc=><DocumentRow key={doc.id} doc={doc} admin={admin} suggestions={suggestions} onUpdate={updated=>setDocs(current=>current.map(item=>item.id===updated.id?updated:item))}/>)}</tbody></table></div>:!error&&<p className={styles.help}>{docs.length?'No documents match your search.':'No documents yet.'}</p>}</>}{error&&<div role="alert" className={styles.error}>{error} <button type="button" className="secondary" disabled={pending} onClick={()=>setReload(value=>value+1)}>Refresh documents</button></div>}{success&&<p role="status" className={styles.help}>{success}</p>}{admin&&<form ref={form} className={styles.upload} onSubmit={upload}><h3>Upload a document</h3><fieldset disabled={pending||loading}><label className={styles.file}>File<input name="file" type="file" required accept=".pdf,.docx,.xlsx,.csv,.txt,.png,.jpg,.jpeg"/></label><p className={styles.help}>PDF, Word, Excel, CSV, text or images · up to 20 MB</p><TagEditor tags={tags} onChange={setTags} suggestions={suggestions} disabled={pending}/><div className={styles.actions}><button disabled={pending||loading}>{pending?'Uploading…':'Upload document'}</button></div></fieldset></form>}</div>;
}
