'use client';
import {applySyncedField,projection} from '@/lib/notion-sync-fields';
import type {PropertyDraft} from '@/lib/schema';
import {factDefinitions,fieldStates,offeringStatuses,type FactDefinition,type FactKey,type PropertyFact} from '@/lib/property-facts';
type Props={draft:PropertyDraft;onChange:(patch:Partial<PropertyDraft>)=>void};
const unknown={state:'Not yet determined' as const,value:null};
function FactInput({label,definition={},value,onChange}:{label:string;definition?:Partial<FactDefinition>;value?:PropertyFact;onChange:(v:PropertyFact|undefined)=>void}){
 const current:PropertyFact=value??unknown;
 const update=(v:PropertyFact['value'])=>onChange({...current,value:v,state:v===null?'Not yet determined':current.state==='Not yet determined'?'Actual':current.state});
 return <div className="cms-content-section form"><label>{label}{definition.options?<select value={String(current.value??'')} onChange={e=>update(e.target.value||null)}><option value="">Not entered</option>{definition.options.map(v=><option key={v}>{v}</option>)}</select>:definition.type==='boolean'?<select value={current.value===null?'':String(current.value)} onChange={e=>update(e.target.value===''?null:e.target.value==='true')}><option value="">Not entered</option><option value="true">Yes</option><option value="false">No</option></select>:definition.type==='number'||definition.type==='money'?<input type="number" step="any" value={typeof current.value==='number'?current.value:''} onChange={e=>update(e.target.value===''?null:Number(e.target.value))}/>:<textarea rows={2} value={Array.isArray(current.value)?current.value.join(', '):String(current.value??'')} onChange={e=>update(e.target.value?(definition.type==='tags'?e.target.value.split(',').map(s=>s.trim()).filter(Boolean):e.target.value):null)}/>}</label><label>State<select value={current.state} onChange={e=>onChange({...current,state:e.target.value as PropertyFact['state']})}>{fieldStates.map(v=><option key={v}>{v}</option>)}</select></label><label>Context / qualification<input value={current.notes??''} onChange={e=>onChange({...current,notes:e.target.value})}/></label>{value&&<button className="text" type="button" onClick={()=>onChange(undefined)}>Clear field</button>}</div>;
}
export function PropertyFactsEditor({draft:d,onChange:set}:Props){
 const groups=[...new Set(Object.values(factDefinitions).map(v=>v.group))];
 return <section className="form"><h2>Property facts</h2><p>Prices and budgets are public when this draft is published. Leave absent facts empty; use “Not yet determined” when that uncertainty should appear on the page.</p>
 <div className="cms-form-grid"><label>Record type<select value={d.recordType} onChange={e=>set({recordType:e.target.value as PropertyDraft['recordType']})}><option value="property">Specific property</option><option value="scouting-area">Scouting area</option></select></label><label>Offering status<select value={d.offeringStatus??''} onChange={e=>set({offeringStatus:e.target.value as PropertyDraft['offeringStatus']||null})}><option value="">Choose status</option>{offeringStatuses.map(v=><option key={v}>{v}</option>)}</select></label><label>Currency<select value={d.currency} onChange={e=>set({currency:e.target.value as PropertyDraft['currency']})}>{['USD','CAD','MXN','EUR','GBP','CRC'].map(v=><option key={v}>{v}</option>)}</select></label></div>
 {d.source&&<aside className="cms-hint"><p>Initially imported from <a href={d.source.url} target="_blank" rel="noreferrer">Notion</a>. Source status: {d.source.sourceStatus}. Subsequent imports preserve app edits.</p>{d.source.reviewNotes.map((n,i)=><p key={i}>{n}</p>)}</aside>}
 {d.source?.sync&&<aside className="cms-content-section"><h3>Notion sync review</h3>{d.source.sync.missing&&<p role="alert">This property is missing from the Notion results. It may have been removed, archived or become inaccessible. The app record and public page are retained.</p>}{d.source.sync.contentReview&&<p>Review page text and media in Notion. Sync updates mapped database fields; it does not rewrite the property story, plans or images.</p>}{d.source.sync.conflicts.map(c=><div className="cms-content-section" key={c.field}><h4>{c.field.replaceAll('_',' ')}</h4><p>App: {JSON.stringify(projection(d)[c.field])}</p><p>Notion: {JSON.stringify(c.notion)}</p><div className="row-actions">{(['Keep app value','Use Notion value'] as const).map(label=><button type="button" className="secondary" key={label} onClick={()=>{const next=label==='Use Notion value'?applySyncedField(d,c.field,c.notion):d;const source=next.source!;set({...next,source:{...source,sync:{...source.sync!,baseline:{...source.sync!.baseline,[c.field]:c.notion},conflicts:source.sync!.conflicts.filter(v=>v.field!==c.field)}}});}}>{label}</button>)}</div></div>)}<p className="cms-hint">Save the draft to keep conflict decisions. Published content changes only when you publish.</p></aside>}
 {groups.map(group=><details className="cms-content-section" key={group}><summary>{group}</summary><div className="cms-form-grid">{Object.entries(factDefinitions).filter(([,v])=>v.group===group).map(([key,def])=><FactInput key={key} label={def.label} definition={def} value={d.facts[key as FactKey]} onChange={value=>{const facts={...d.facts};if(value)facts[key as FactKey]=value;else delete facts[key as FactKey];set({facts});}}/>)}</div></details>)}
 <details className="cms-content-section"><summary>Map coordinates</summary><div className="form">{(['latitude','longitude'] as const).map(key=><label key={key}>{key}<input type="number" step="any" value={Number.isFinite(d.coordinates?.value?.[key])?d.coordinates!.value![key]:''} onChange={e=>{const value=d.coordinates?.value??{latitude:NaN,longitude:NaN,precision:'approximate' as const};set({coordinates:{state:'Actual',value:{...value,[key]:e.target.value===''?NaN:Number(e.target.value)}}});}}/></label>)}<label>Precision<select value={d.coordinates?.value?.precision??'approximate'} onChange={e=>{if(d.coordinates?.value)set({coordinates:{...d.coordinates,value:{...d.coordinates.value,precision:e.target.value as 'approximate'|'parcel'}}});}}><option value="approximate">Approximate region</option><option value="parcel">Property location</option></select></label><button type="button" className="text" onClick={()=>set({coordinates:null})}>Clear coordinates</button></div></details>
 <details className="cms-content-section"><summary>Nearby places</summary>{d.proximity.map((p,i)=>{const update=(patch:Partial<typeof p>)=>set({proximity:d.proximity.map((v,j)=>j===i?{...v,...patch}:v)});return <div className="cms-content-section form" key={p.id}><label>Name<input value={p.name} onChange={e=>update({name:e.target.value})}/></label><label>Kind<select value={p.kind} onChange={e=>update({kind:e.target.value as typeof p.kind})}>{['airport','town','metro','anchor'].map(v=><option key={v}>{v}</option>)}</select></label><FactInput label="Travel minutes" definition={{type:'number'}} value={p.minutes} onChange={v=>update({minutes:(v??unknown) as typeof p.minutes})}/><FactInput label="Miles" definition={{type:'number'}} value={p.miles} onChange={v=>update({miles:(v??unknown) as typeof p.miles})}/><label>Notes<textarea value={p.notes} onChange={e=>update({notes:e.target.value})}/></label><button className="text" type="button" onClick={()=>set({proximity:d.proximity.filter((_,j)=>j!==i)})}>Remove place</button></div>;})}<button type="button" className="secondary" onClick={()=>set({proximity:[...d.proximity,{id:crypto.randomUUID(),name:'New place',kind:'town',minutes:unknown,miles:unknown,notes:''}]})}>Add nearby place</button></details>
 <details className="cms-content-section"><summary>Financial phases</summary>{d.phases.map((p,i)=>{const update=(patch:Partial<typeof p>)=>set({phases:d.phases.map((v,j)=>j===i?{...v,...patch}:v)});return <div className="cms-content-section form" key={p.id}><label>Name<input value={p.name} onChange={e=>update({name:e.target.value})}/></label><label>Scope<textarea value={p.scope} onChange={e=>update({scope:e.target.value})}/></label><FactInput label={`Budget (${d.currency})`} definition={{type:'money'}} value={p.budget} onChange={v=>update({budget:(v??unknown) as typeof p.budget})}/><FactInput label="Timeline" value={p.timeline} onChange={v=>update({timeline:(v??unknown) as typeof p.timeline})}/><button type="button" className="text" onClick={()=>set({phases:d.phases.filter((_,j)=>j!==i)})}>Remove phase</button></div>;})}<button type="button" className="secondary" onClick={()=>set({phases:[...d.phases,{id:crypto.randomUUID(),name:'New phase',scope:'',budget:unknown,timeline:unknown}]})}>Add phase</button></details>
 </section>;
}
