import type {PropertyDraft} from '@/lib/schema';
import {factDefinitions,formatFact,travelTime,type FactKey,type FactDefinition} from '@/lib/property-facts';
export function PropertyFacts({property:p}:{property:PropertyDraft}){
 const groups=[...new Set(Object.values(factDefinitions).map(v=>v.group))];
 return <div id="property-facts">{groups.map(group=>{const entries=Object.entries(factDefinitions).filter(([key,d])=>d.group===group&&p.facts[key as FactKey]);if(!entries.length)return null;return <section className="section split" key={group}><h2>{group}</h2><dl className="buyer-specs">{entries.map(([key,d])=>{const f=p.facts[key as FactKey]!;return <div key={key}><dt>{d.label}</dt><dd>{formatFact(f,p.currency,(d as FactDefinition).type==='money')}{f.notes&&<p className="caption">{f.notes}</p>}</dd></div>;})}</dl></section>;})}
 {p.proximity.length>0&&<section className="section"><h2>Getting here & nearby</h2>{(['airport','town','metro','anchor'] as const).map(kind=>{const places=p.proximity.filter(v=>v.kind===kind);return places.length>0&&<div key={kind}><h3>{kind==='anchor'?'Nearby attractions':kind==='metro'?'Cities':kind==='airport'?'Airports':'Towns'}</h3><dl className="buyer-specs">{places.map(v=><div key={v.id}><dt>{v.name}</dt><dd>{v.minutes.value!==null&&v.minutes.state!=='Not yet determined'?`${travelTime(v.minutes.value)}${v.minutes.state==='Planned'?' (planned)':''}`:'Travel time not yet determined'}{v.miles.value!==null&&v.miles.state!=='Not yet determined'?` · ${v.miles.value} miles${v.miles.state==='Planned'?' (planned)':''}`:''}{v.notes&&<p className="caption">{v.notes}</p>}</dd></div>)}</dl></div>;})}</section>}
 {p.phases.length>0&&<section className="section"><h2>Financials & phasing</h2>{p.phases.map(v=><article className="cms-content-section" key={v.id}><h3>{v.name}</h3><p>{v.scope}</p><dl className="buyer-specs"><div><dt>Budget</dt><dd>{formatFact(v.budget,p.currency,true)}{v.budget.notes&&<p className="caption">{v.budget.notes}</p>}</dd></div><div><dt>Timeline</dt><dd>{formatFact(v.timeline)}{v.timeline.notes&&<p className="caption">{v.timeline.notes}</p>}</dd></div></dl></article>)}</section>}
 {p.media.length>0&&<section className="section"><h2>Plans & media</h2><div className="cms-public-gallery">{p.media.map(v=><figure key={v.id}>{v.kind==='image'?<img src={v.url} alt={v.alt} loading="lazy"/>:v.kind==='video'?<video controls preload="metadata" src={v.url} aria-label={v.alt}/>:<a href={v.url} target="_blank" rel="noreferrer">{v.alt}</a>}<figcaption><span className="badge">{v.role.replaceAll('_',' ')} · {v.state}</span><p>{v.caption}</p></figcaption></figure>)}</div></section>}
 </div>;
}
