'use client';
import {useEffect,useRef,useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {type PropertyDraft,type PropertyRecord,imageLibrary} from '@/lib/schema';
import {saveProperty,publishProperty,unpublishProperty} from '@/app/staff/properties/actions';
type History={id:string;action:string;actor:string;version:number;created_at:string}[];
export function PropertyEditor({initial,history}:{initial:PropertyRecord;history:History}){
 const [record,setRecord]=useState(initial),[draft,setDraft]=useState(initial.draft),[tab,setTab]=useState('Overview'),[feedback,setFeedback]=useState(''),[error,setError]=useState(''),[confirmation,setConfirmation]=useState<'publish'|'unpublish'|null>(null),[pending,start]=useTransition();const router=useRouter();
 const dirty=JSON.stringify(draft)!==JSON.stringify(record.draft);
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(confirmation)dialog.current?.showModal();else dialog.current?.close();},[confirmation]);
 useEffect(()=>{function guard(e:BeforeUnloadEvent){if(dirty){e.preventDefault();e.returnValue='';}}window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
 const set=<K extends keyof PropertyDraft>(key:K,value:PropertyDraft[K])=>{setDraft(p=>({...p,[key]:value}));setFeedback('');};
 const field=(label:string,key:'name'|'slug'|'region'|'status'|'headline'|'summary'|'intro'|'imageAlt',multiline=false)=><label>{label}{multiline?<textarea value={draft[key]} rows={key==='intro'?6:3} onChange={e=>set(key,e.target.value)} required/>:<input value={draft[key]} onChange={e=>set(key,e.target.value)} required/>}</label>;
 function run(action:'save'|'publish'|'unpublish'){start(async()=>{setError('');setFeedback('');const result=action==='save'?await saveProperty(record.id,record.version,draft):action==='publish'?await publishProperty(record.id,record.version):await unpublishProperty(record.id,record.version);if(!result.ok){setError(result.error);return;}setRecord(result.record);setDraft(result.record.draft);setConfirmation(null);setFeedback(action==='save'?'Draft saved. The published page has not changed.':action==='publish'?'Published. The public page now shows this version.':'Unpublished. The public page is no longer available.');router.refresh();});}
 const section=(index:number,patch:Partial<PropertyDraft['sections'][number]>)=>set('sections',draft.sections.map((s,i)=>i===index?{...s,...patch}:s));
 return <><a href="/staff/properties" onClick={e=>{if(dirty&&!confirm('Leave this page and discard unsaved edits?'))e.preventDefault();}}>Property content</a><div className="heading cms-editor-heading"><div><div className="eyebrow">{record.published?'PUBLISHED PROPERTY':'DRAFT PROPERTY'} · REVISION {record.version}</div><h1>{record.draft.name}</h1></div><span className="cms-save-state">{dirty?'Unsaved changes':'All changes saved'}</span></div>
 <div className="cms-toolbar"><div role="tablist" aria-label="Editor sections">{['Overview','Content','Photos','History'].map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'active':'secondary'} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="row-actions"><button disabled={pending||!dirty} onClick={()=>run('save')}>{pending?'Working…':'Save draft'}</button><a className="button secondary" href={'/staff/properties/'+record.id+'/preview'} target="_blank" rel="noreferrer">Preview saved draft</a><button className="secondary" disabled={pending||dirty} onClick={()=>setConfirmation('publish')}>Publish…</button></div></div>
 {dirty&&<p className="cms-hint">Save your changes before previewing or publishing.</p>}{feedback&&<div role="status" className="cms-success">{feedback}</div>}{error&&<div role="alert" className="cms-error">{error}</div>}
 <fieldset className="cms-fields" disabled={pending}>
 {tab==='Overview'&&<div className="cms-form-grid"><section className="form"><h2>The property at a glance.</h2>{field('Property name','name')}{field('Page address','slug')}<p className="cms-hint">/properties/{draft.slug}</p>{field('Region','region')}<label>Landscape<select value={draft.category} onChange={e=>set('category',e.target.value as PropertyDraft['category'])}>{['Mountains','Farms','Coast','Desert'].map(c=><option key={c}>{c}</option>)}</select></label>{field('Property status','status')}<label className="cms-checkbox"><input type="checkbox" checked={draft.isDemo} onChange={e=>set('isDemo',e.target.checked)}/>Label as demo content</label><p className="cms-hint">Keep this enabled while property facts, prices and availability are fictional.</p></section><section className="form"><h2>The opening story.</h2>{field('Hero headline','headline')}{field('Short description','summary',true)}{field('Introduction','intro',true)}</section></div>}
 {tab==='Content'&&<section><div className="heading"><div><h2>The full story.</h2><p>Use sections for land details, building plans, ownership costs and buyer information.</p></div><button className="secondary" onClick={()=>set('sections',[...draft.sections,{id:'section-'+crypto.randomUUID().slice(0,8),eyebrow:'',title:'New section',body:'',facts:[]}])}>+ Add section</button></div>{draft.sections.map((s,i)=><details className="cms-content-section" key={s.id} open={undefined}><summary><span>{String(i+1).padStart(2,'0')}</span>{s.title}</summary><div className="form"><label>Section label<input value={s.eyebrow} onChange={e=>section(i,{eyebrow:e.target.value})}/></label><label>Title<input value={s.title} onChange={e=>section(i,{title:e.target.value})}/></label><label>Story<textarea rows={5} value={s.body} onChange={e=>section(i,{body:e.target.value})}/></label><h3>Details</h3>{s.facts.map((f,j)=><div className="cms-fact-editor" key={j}><label>Label<input value={f.label} onChange={e=>section(i,{facts:s.facts.map((v,k)=>k===j?{...v,label:e.target.value}:v)})}/></label><label>Value<textarea rows={2} value={f.value} onChange={e=>section(i,{facts:s.facts.map((v,k)=>k===j?{...v,value:e.target.value}:v)})}/></label><button className="secondary" aria-label={'Remove detail '+(j+1)+' from '+s.title} onClick={()=>section(i,{facts:s.facts.filter((_,k)=>k!==j)})}>Remove</button></div>)}<div className="row-actions"><button className="secondary" onClick={()=>section(i,{facts:[...s.facts,{label:'New detail',value:'Add information'}]})}>+ Add detail</button><button className="secondary" disabled={i===0} onClick={()=>{const sections=[...draft.sections];[sections[i-1],sections[i]]=[sections[i],sections[i-1]];set('sections',sections);}}>Move up</button><button className="secondary" disabled={i===draft.sections.length-1} onClick={()=>{const sections=[...draft.sections];[sections[i+1],sections[i]]=[sections[i],sections[i+1]];set('sections',sections);}}>Move down</button><button className="text" onClick={()=>{if(confirm('Remove this section from the draft? The published version will stay unchanged until you publish.'))set('sections',draft.sections.filter((_,k)=>k!==i));}}>Remove section</button></div></div></details>)}</section>}
 {tab==='Photos'&&<section className="form"><h2>Images with context.</h2><p>Choose from the current image library. Keep regional and inspiration imagery clearly identified.</p><label>Cover image<select value={draft.hero} onChange={e=>set('hero',e.target.value)}>{imageLibrary.map(im=><option key={im.src} value={im.src}>{im.label}</option>)}</select></label><img className="cms-cover-preview" src={draft.hero} alt={draft.imageAlt}/>{field('Cover image description','imageAlt')}<h3>Gallery</h3>{draft.gallery.map((g,i)=><div className="cms-gallery-editor" key={i}><img src={g.src} alt={g.alt}/><div className="form"><label>Image<select value={g.src} onChange={e=>set('gallery',draft.gallery.map((v,j)=>j===i?{...v,src:e.target.value}:v))}>{imageLibrary.map(im=><option key={im.src} value={im.src}>{im.label}</option>)}</select></label><label>Image description<input value={g.alt} onChange={e=>set('gallery',draft.gallery.map((v,j)=>j===i?{...v,alt:e.target.value}:v))}/></label><label>Caption<textarea value={g.caption} onChange={e=>set('gallery',draft.gallery.map((v,j)=>j===i?{...v,caption:e.target.value}:v))}/></label><label>Image type<select value={g.type} onChange={e=>set('gallery',draft.gallery.map((v,j)=>j===i?{...v,type:e.target.value as typeof g.type}:v))}>{['Regional','Inspiration','Current property','Proposed'].map(t=><option key={t}>{t}</option>)}</select></label><button className="secondary" onClick={()=>set('gallery',draft.gallery.filter((_,j)=>j!==i))}>Remove image</button></div></div>)}<button className="secondary" onClick={()=>set('gallery',[...draft.gallery,{src:'/images/landscape.png',alt:'Donner Lake regional reference',caption:'Regional photograph; not a verified property view.',type:'Regional'}])}>+ Add gallery image</button></section>}
 {tab==='History'&&<section><h2>A record of the work.</h2><p>Every saved draft and publication change is recorded.</p><ol className="cms-history">{history.map(h=><li key={h.id}><strong>{h.action[0].toUpperCase()+h.action.slice(1)} · revision {h.version}</strong><span>{new Date(h.created_at).toLocaleString()} · {h.actor==='local-developer'?'Local editor':h.actor==='demo-seed'?'Demo content import':h.actor}</span></li>)}</ol></section>}
 </fieldset><div className="cms-publication-state"><p>{record.published?<>Published at <a href={'/properties/'+record.published.slug} target="_blank" rel="noreferrer">/properties/{record.published.slug}</a></>:'This property has no public page yet.'}</p>{record.published&&<button className="secondary" disabled={pending||dirty} onClick={()=>setConfirmation('unpublish')}>Unpublish…</button>}</div>
 {confirmation&&<dialog ref={dialog} className="cms-confirm" aria-labelledby="confirm-title" onCancel={()=>setConfirmation(null)}><h2 id="confirm-title">{confirmation==='publish'?'Publish this saved draft?':'Take this page offline?'}</h2><p>{confirmation==='publish'?'The saved draft will become the public version on this site. Future edits will remain private until published again.':'The public page will no longer be available. Your draft and change history will be preserved.'}</p>{draft.isDemo&&confirmation==='publish'&&<p>The demo-content label will stay visible.</p>}<div className="row-actions"><button autoFocus disabled={pending} className="secondary" onClick={()=>setConfirmation(null)}>Cancel</button><button disabled={pending} onClick={()=>run(confirmation)}>{pending?'Working…':confirmation==='publish'?'Publish property':'Unpublish property'}</button></div></dialog>}
 </>;
}
