'use client';
import {useState,useTransition} from 'react';
import {propertyRoleValues,propertyRoleLabels,type PropertyRole,type MemberProperty,type MemberInfo} from '@/lib/member-properties';
import {saveMemberInfo,saveMemberProperty} from './actions';
import {PropertyPicker} from './property-picker';
export function MemberInfoEditor({userId,initial}:{userId:string;initial:MemberInfo}){
 const [info,setInfo]=useState(initial),[message,setMessage]=useState(''),[error,setError]=useState('');const [pending,start]=useTransition();
 return <form className="form dashboard-form" onSubmit={e=>{e.preventDefault();setError('');setMessage('');start(async()=>{try{const result=await saveMemberInfo(userId,info);setError(result.error||'');setMessage(result.message||'');}catch{setError('Unable to save. Please try again.');}});}}><fieldset disabled={pending} className="member-detail-fields"><label>Name<input required maxLength={100} value={info.displayName} onChange={e=>setInfo({...info,displayName:e.target.value})}/></label><label>Home region<input maxLength={100} value={info.homeRegion} onChange={e=>setInfo({...info,homeRegion:e.target.value})}/></label><label>Contact phone<input type="tel" maxLength={50} value={info.contactPhone} onChange={e=>setInfo({...info,contactPhone:e.target.value})}/></label></fieldset><button disabled={pending}>{pending?'Saving…':'Save member information'}</button>{error&&<p role="alert" className="cms-error">{error}</p>}{message&&<p role="status" className="cms-success">{message}</p>}</form>;
}
export function MemberProperties({userId,initial,properties}:{userId:string;initial:MemberProperty[];properties:{id:string;name:string}[]}){
 const [rows,setRows]=useState(initial);const [propertyId,setPropertyId]=useState('');const [roles,setRoles]=useState<PropertyRole[]>(['prospect']);const [message,setMessage]=useState('');const [error,setError]=useState('');const [pending,start]=useTransition();
 const available=properties.filter(p=>!rows.some(row=>row.property_id===p.id));
 function save(propertyId:string,roles:PropertyRole[],version?:number,remove=false){setError('');setMessage('');start(async()=>{try{const result=await saveMemberProperty({userId,propertyId,roles,version,remove});if(result.error)setError(result.error);else if(result.associations){setRows(result.associations);setMessage(result.message||'Saved.');setPropertyId('');}}catch{setError('Unable to save. Please try again.');}});}
 return <><p>Assign one or more roles for each property. These associations are separate from club-wide roles and do not grant Admin access or establish legal ownership or booking rights.</p>{rows.length?rows.map(row=><Association key={`${row.property_id}:${row.version}`} row={row} pending={pending} save={save}/>):<p className="notice">No properties are associated with this member yet.</p>}<h3>Add a property</h3>{available.length?<form className="form" onSubmit={e=>{e.preventDefault();save(propertyId,roles);}}><div className="dashboard-grid member-property-add-grid"><PropertyPicker properties={available} value={propertyId} onChange={setPropertyId} disabled={pending}/><PropertyRolePicker label="Roles on this property" roles={roles} onChange={setRoles} disabled={pending}/></div><button disabled={pending||!propertyId||!roles.length}>{pending?'Saving…':'Add property'}</button></form>:<p className="muted">{properties.length?'All available properties are already associated.':'Create a property in Property content first.'}</p>}{error&&<p role="alert" className="cms-error">{error}</p>}{message&&<p role="status" className="cms-success">{message}</p>}</>;
}
function Association({row,pending,save}:{row:MemberProperty;pending:boolean;save:(id:string,roles:PropertyRole[],version?:number,remove?:boolean)=>void}){
 const [roles,setRoles]=useState(row.roles);const [confirm,setConfirm]=useState(false);
 return <article className="member-property-row"><div><h3>{row.name}</h3><p className="muted">{row.region}</p></div><PropertyRolePicker label={`Roles at ${row.name}`} roles={roles} onChange={setRoles} disabled={pending}/><div className="row-actions"><button className="secondary" disabled={pending||!roles.length||(roles.length===row.roles.length&&roles.every(role=>row.roles.includes(role)))} onClick={()=>save(row.property_id,roles,row.version)}>Save roles</button><button className="secondary" disabled={pending} onClick={()=>setConfirm(!confirm)}>Remove</button></div>{confirm&&<div className="notice"><p>Remove this member’s association with {row.name}? You can add it again later.</p><div className="row-actions"><button disabled={pending} onClick={()=>save(row.property_id,row.roles,row.version,true)}>Confirm removal</button><button className="secondary" disabled={pending} onClick={()=>setConfirm(false)}>Keep association</button></div></div>}</article>;
}

function PropertyRolePicker({label,roles,onChange,disabled}:{label:string;roles:PropertyRole[];onChange:(roles:PropertyRole[])=>void;disabled:boolean}){
 return <fieldset className="property-role-picker" disabled={disabled}><legend>{label}</legend><p className="muted">Select all that apply.</p><div>{propertyRoleValues.map(role=><label key={role}><input type="checkbox" checked={roles.includes(role)} onChange={e=>onChange(e.target.checked?[...roles,role]:roles.filter(value=>value!==role))}/>{propertyRoleLabels[role]}</label>)}</div>{!roles.length&&<p className="muted">Select at least one role.</p>}</fieldset>;
}
