'use client';
import {useState,useTransition} from 'react';
import {propertyRoleValues,propertyRoleLabels,type PropertyRole,type MemberProperty,type MemberInfo} from '@/lib/member-properties';
import {saveMemberInfo,saveMemberProperty} from './actions';
export function MemberInfoEditor({userId,initial}:{userId:string;initial:MemberInfo}){
 const [info,setInfo]=useState(initial),[message,setMessage]=useState(''),[error,setError]=useState('');const [pending,start]=useTransition();
 return <form className="form dashboard-form" onSubmit={e=>{e.preventDefault();setError('');setMessage('');start(async()=>{try{const result=await saveMemberInfo(userId,info);setError(result.error||'');setMessage(result.message||'');}catch{setError('Unable to save. Please try again.');}});}}><fieldset disabled={pending} className="member-detail-fields"><label>Name<input required maxLength={100} value={info.displayName} onChange={e=>setInfo({...info,displayName:e.target.value})}/></label><label>Home region<input maxLength={100} value={info.homeRegion} onChange={e=>setInfo({...info,homeRegion:e.target.value})}/></label><label>Contact phone<input type="tel" maxLength={50} value={info.contactPhone} onChange={e=>setInfo({...info,contactPhone:e.target.value})}/></label></fieldset><button disabled={pending}>{pending?'Saving…':'Save member information'}</button>{error&&<p role="alert" className="cms-error">{error}</p>}{message&&<p role="status" className="cms-success">{message}</p>}</form>;
}
export function MemberProperties({userId,initial,properties}:{userId:string;initial:MemberProperty[];properties:{id:string;name:string}[]}){
 const [rows,setRows]=useState(initial);const [propertyId,setPropertyId]=useState('');const [role,setRole]=useState<PropertyRole>('prospect');const [message,setMessage]=useState('');const [error,setError]=useState('');const [pending,start]=useTransition();
 const available=properties.filter(p=>!rows.some(row=>row.property_id===p.id));
 function save(propertyId:string,role:PropertyRole,version?:number,remove=false){setError('');setMessage('');start(async()=>{try{const result=await saveMemberProperty({userId,propertyId,role,version,remove});if(result.error)setError(result.error);else if(result.associations){setRows(result.associations);setMessage(result.message||'Saved.');setPropertyId('');}}catch{setError('Unable to save. Please try again.');}});}
 return <><p>Assign a role for each property. These associations are separate from club-wide roles and do not grant Admin access or establish legal ownership or booking rights.</p>{rows.length?rows.map(row=><Association key={`${row.property_id}:${row.version}`} row={row} pending={pending} save={save}/>):<p className="notice">No properties are associated with this member yet.</p>}<h3>Add a property</h3>{available.length?<form className="form" onSubmit={e=>{e.preventDefault();save(propertyId,role);}}><div className="dashboard-grid"><label>Property<select required disabled={pending} value={propertyId} onChange={e=>setPropertyId(e.target.value)}><option value="">Choose a property</option>{available.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Role on this property<select disabled={pending} value={role} onChange={e=>setRole(e.target.value as PropertyRole)}>{propertyRoleValues.map(r=><option key={r} value={r}>{propertyRoleLabels[r]}</option>)}</select></label></div><button disabled={pending||!propertyId}>{pending?'Saving…':'Add property'}</button></form>:<p className="muted">{properties.length?'All available properties are already associated.':'Create a property in Property content first.'}</p>}{error&&<p role="alert" className="cms-error">{error}</p>}{message&&<p role="status" className="cms-success">{message}</p>}</>;
}
function Association({row,pending,save}:{row:MemberProperty;pending:boolean;save:(id:string,role:PropertyRole,version?:number,remove?:boolean)=>void}){
 const [role,setRole]=useState(row.role);const [confirm,setConfirm]=useState(false);
 return <article className="member-property-row"><div><h3>{row.name}</h3><p className="muted">{row.region}</p></div><label>Property role<select aria-label={`Role at ${row.name}`} disabled={pending} value={role} onChange={e=>setRole(e.target.value as PropertyRole)}>{propertyRoleValues.map(r=><option key={r} value={r}>{propertyRoleLabels[r]}</option>)}</select></label><div className="row-actions"><button className="secondary" disabled={pending||role===row.role} onClick={()=>save(row.property_id,role,row.version)}>Save role</button><button className="secondary" disabled={pending} onClick={()=>setConfirm(!confirm)}>Remove</button></div>{confirm&&<div className="notice"><p>Remove this member’s association with {row.name}? You can add it again later.</p><div className="row-actions"><button disabled={pending} onClick={()=>save(row.property_id,row.role,row.version,true)}>Confirm removal</button><button className="secondary" disabled={pending} onClick={()=>setConfirm(false)}>Keep association</button></div></div>}</article>;
}
